# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Job_Build
        steps:
          - task: Bash@3
            inputs:
              targetType: inline
              script: |
                # Write your commands here                  
                echo 'Hello world.'
  
  - stage: Test
    dependsOn:
      - Build
    jobs:
      - job: Job_Test
        steps:
          - task: Bash@3
            inputs:
              targetType: inline
              script: |
                # Write your commands here                  
                echo 'Hello world'
          - task: Maven@3
            inputs:
              mavenPomFile: pom.xml
              goals: test
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              testRunTitle: Job_Test
              javaHomeOption: JDKVersion
              mavenVersionOption: Default
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

          # - task: ServiceNow-DevOps-Build-Security-Results@1
          #   inputs:
          #     connectedServiceName: 'devopsqerama92-Basic Project1-ServiceNow DevOps Service Connection'
          #     securityResultAttributes: |
          #       {
          #       "scanner": "CheckmarxOne", #Scanning tool and is required e.g. CheckmarxOne.
          #       "projectName": "DemoProject", #Name of your CheckMarxOne project and is required. This attribute is applicable only for CheckmarxOne.
          #       "projectId": "75acb348-c054-4ab3-807d-e17e92a923ab", #Id of your CheckMarxOne project and can be used instead of projectName field. This attribute is applicable only for CheckmarxOne.
          #       "scanId": "c8053f9d-8047-44ae-8972-dc5176b7dd67", #CheckmarxOne scan id and is optional. This attribute is applicable only for CheckmarxOne.
          #       "securityToolId": "b8d81b8fc3bc7110c825371f05013174" #Security tool onboarded in ServiceNow (sys_id of the onboarded security tool) and is optional.
          #       }

  - stage: Deploy
    dependsOn: Test
    jobs:
      - job: Job_Deploy
        steps:
          - task: Bash@3
            inputs:
              targetType: inline
              script: |
                # Write your commands here                  
                echo 'Hello world'
          - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
            inputs:
              connectedServiceName: 'devopsqerama92-Basic Project1-ServiceNow DevOps Service Connection'
              artifactsPayload: |
                {
                    "artifacts":
                    [
                    {
                        "name": "alpha",
                        "repositoryName": "$(build.definitionName)",
                        "version": "1.$(build.buildId)",
                        "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                        "taskExecutionNumber":"$(build.buildId)",
                        "stageName":"$(system.jobDisplayName)",
                        "branchName":"$(build.sourceBranchName)"
                    },
                    {
                        "name": "beta",
                        "repositoryName": "$(build.definitionName)",
                        "version": "1.$(build.buildId)",
                        "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                        "taskExecutionNumber":"$(build.buildId)",
                        "stageName":"$(system.jobDisplayName)",
                        "branchName":"$(build.sourceBranchName)"
                    },
                    {
                        "name": "gamma",
                        "repositoryName": "$(build.definitionName)",
                        "version": "1.$(build.buildId)",
                        "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                        "taskExecutionNumber":"$(build.buildId)",
                        "stageName":"$(system.jobDisplayName)",
                        "branchName":"$(build.sourceBranchName)"
                    }]
                }
          - task: ServiceNow-DevOps-Agent-Package-Registration@1
            inputs:
              connectedServiceName: 'devopsqerama92-Basic Project1-ServiceNow DevOps Service Connection'
              packageName: 'package-devops-3.0.0-SNAPSHOT.zip'
              artifactsPayload: |
                {
                    "artifacts": [
                    {
                        "name": "alpha",
                        "repositoryName": "DevOps-Test",
                        "version": "1.$(build.buildId)",
                        "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                        "taskExecutionNumber":"$(build.buildId)",
                        "stageName":"$(system.jobDisplayName)",
                        "branchName":"$(build.sourceBranchName)"
                    },
                    {
                        "name": "beta",
                        "repositoryName": "DevOps-Test",
                        "version": "1.$(build.buildId)",
                        "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                        "taskExecutionNumber":"$(build.buildId)",
                        "stageName":"$(system.jobDisplayName)",
                        "branchName":"$(build.sourceBranchName)"
                    },
                    {
                        "name": "gamma",
                        "repositoryName": "DevOps-Test",
                        "version": "1.$(build.buildId)",
                        "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                        "taskExecutionNumber":"$(build.buildId)",
                        "stageName":"$(system.jobDisplayName)",
                        "branchName":"$(build.sourceBranchName)"
                    }],
                    "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                    "taskExecutionNumber":"$(build.buildId)",
                    "stageName":"$(system.jobDisplayName)",
                    "branchName":"$(build.sourceBranchName)"
                }
  - stage: Prod
    dependsOn: Deploy
    jobs:
      - job: Job_Prod
        pool:
          name: server
        steps:
          - task: ServiceNow-DevOps-Server-Change-Acceleration@1
            inputs:
              connectedServiceName: 'devopsqerama92-Basic Project1-ServiceNow DevOps Service Connection'
              UpstreamJob: 'Job_Deploy'
              changeRequestDetails: |
                {
                  "setCloseCode": false,
                  "attributes": {
                    "requested_by": {
                        "name": "DevOps System"
                    },
                    "category": "DevOps",
                    "priority": "2",
                    "start_date": "2022-01-05 11:59:59",
                    "end_date": "2022-01-08 11:59:59"
                    }
                }
  
  # - stage: GETUPDATEchange
  #   dependsOn: Prod
  #   jobs:
  #     - job: Job_GETUPDATEchange
  #       steps:
  #         - task: Bash@3
  #           inputs:
  #             targetType: inline
  #             script: |
  #               # Write your commands here                  
  #               echo 'Hello world'
  #         - task: ServiceNow-DevOps-Agent-Get-Change@1
  #           inputs:
  #             connectedServiceName: 'devopsqerama92-Basic Project1-ServiceNow DevOps Service Connection'
  #             projectName: '$(system.teamProject)'
  #             pipelineName: '$(build.definitionName)'
  #             stageName: '$(System.StageName)'
  #             jobName: '$(System.JobDisplayName)'
  #             buildNumber: '$(build.buildId)'
  #             attemptNumber: '$(System.JobAttempt)'
  #             branchName: '$(Build.SourceBranchName)'
          
  #         - task: ServiceNow-DevOps-Agent-Update-Change@1
  #           inputs:
  #             connectedServiceName: 'devopsqerama92-Basic Project1-ServiceNow DevOps Service Connection'
  #             changeRequestNumber: 'CHG0030013'
  #             changeRequestDetails: |
  #               {
  #               "short_description": "Updating the short_description",
  #               "work_notes": "updated work notes",
  #               "description": "change description updating"
  #               }