# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:       
  - stage: Prod
    jobs:
      - job: Job_Prod
        pool:
          name: server
        steps:
        # - task: ServiceNow-DevOps-Server-Change-Acceleration@1
        #   inputs:
        #     connectedServiceName: "dsinghu1-Basic Project1-ServiceNow DevOps Service Connection" # ServiceNow DevOps Change Velocity Service Connection

        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: "dsinghu1-Basic Project1-ServiceNow DevOps Service Connection" # ServiceNow DevOps Change Velocity Service Connection
            changeRequestDetails: |
              {
                "attributes": {
                  "requested_by": {
                    "name": "DevOps System"
                  },
                  "assignment_group": {
                    "name": "Change Management"
                  },
                  "priority": "2",
                  "comments": "This is a sample pipeline script to be added in your change step",
                  "work_notes": "Update this to work_notes",
                  "start_date": "2023-09-07 11:59:59",
                  "end_date": "2023-09-09 11:59:59" # This is the planned end date.
                }
              }
 

        # - task: ServiceNow-DevOps-Server-Change-Acceleration@1
        #   inputs:
        #     connectedServiceName: 'dsinghu1-Basic Project1-ServiceNow DevOps Service Connection'
        #     changeRequestDetails: |
        #       {
        #         "autoCloseChange": false,
        #         "attributes": {
        #           "requested_by": {
        #             "name": "DevOps System"
        #           }
        #         }                
        #       }