# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Job_Build
        steps:
          - task: Bash@3
            inputs:
              targetType: inline
              script: |
                # Write your commands here                  
                echo 'Hello world.'
  
  - stage: Test
    dependsOn:
      - Build
    jobs:
      - job: Job_Test
        steps:
          - task: Bash@3
            inputs:
              targetType: inline
              script: |
                # Write your commands here                  
                echo 'Hello world'
          - task: Maven@3
            inputs:
              mavenPomFile: pom.xml
              goals: test
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              testRunTitle: Job_Test
              javaHomeOption: JDKVersion
              mavenVersionOption: Default
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

          - task: ServiceNow-DevOps-Build-Sonar-Registration@1
            inputs:
              connectedServiceName: 'devopstokyo139-Basic Project1-ServiceNow DevOps Service Connection'
              sonarProjectKey: 'pramaraju96_DevOps-Test'
              sonarInstanceUrl: 'https://sonarcloud.io'

          - task: ServiceNow-DevOps-Build-Security-Results@1
            inputs:
              connectedServiceName: 'devopstokyo139-Basic Project1-ServiceNow DevOps Service Connection'
              securityResultAttributes: |
                {
                 "scanner": "Veracode", 
                 "applicationName": "VeraDemo10", 
                 "securityToolId": "12deb11847d5b110bf04bf15126d4354" 
                }

  - stage: Deploy
    dependsOn: Test
    jobs:
      - job: Job_Deploy
        steps:
          - task: Bash@3
            inputs:
              targetType: inline
              script: |
                # Write your commands here                  
                echo 'Hello world'

          - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
            inputs:
              connectedServiceName: 'devopstokyo139-Basic Project1-ServiceNow DevOps Service Connection'
              artifactsPayload: |
                {
                    "artifacts":
                    [
                    {
                        "name": "alpha",
                        "repositoryName": "$(build.definitionName)",
                        "version": "1.$(build.buildId)",
                        "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                        "taskExecutionNumber":"$(build.buildId)",
                        "stageName":"$(system.jobDisplayName)",
                        "branchName":"$(build.sourceBranchName)"
                    },
                    {
                        "name": "beta",
                        "repositoryName": "$(build.definitionName)",
                        "version": "1.$(build.buildId)",
                        "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                        "taskExecutionNumber":"$(build.buildId)",
                        "stageName":"$(system.jobDisplayName)",
                        "branchName":"$(build.sourceBranchName)"
                    },
                    {
                        "name": "gamma",
                        "repositoryName": "$(build.definitionName)",
                        "version": "1.$(build.buildId)",
                        "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                        "taskExecutionNumber":"$(build.buildId)",
                        "stageName":"$(system.jobDisplayName)",
                        "branchName":"$(build.sourceBranchName)"
                    }]
                }
          - task: ServiceNow-DevOps-Agent-Package-Registration@1
            inputs:
              connectedServiceName: 'devopstokyo139-Basic Project1-ServiceNow DevOps Service Connection'
              packageName: 'package-devops-3.0.0-SNAPSHOT.zip'
              artifactsPayload: |
                {
                    "artifacts": [
                    {
                        "name": "alpha",
                        "repositoryName": "$(build.definitionName)",
                        "version": "1.$(build.buildId)",
                        "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                        "taskExecutionNumber":"$(build.buildId)",
                        "stageName":"$(system.jobDisplayName)",
                        "branchName":"$(build.sourceBranchName)"
                    },
                    {
                        "name": "beta",
                        "repositoryName": "$(build.definitionName)",
                        "version": "1.$(build.buildId)",
                        "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                        "taskExecutionNumber":"$(build.buildId)",
                        "stageName":"$(system.jobDisplayName)",
                        "branchName":"$(build.sourceBranchName)"
                    },
                    {
                        "name": "gamma",
                        "repositoryName": "$(build.definitionName)",
                        "version": "1.$(build.buildId)",
                        "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                        "taskExecutionNumber":"$(build.buildId)",
                        "stageName":"$(system.jobDisplayName)",
                        "branchName":"$(build.sourceBranchName)"
                    }],
                    "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                    "taskExecutionNumber":"$(build.buildId)",
                    "stageName":"$(system.jobDisplayName)",
                    "branchName":"$(build.sourceBranchName)"
                }

          
  - stage: Prod
    dependsOn: Deploy
    jobs:
      - job: Job_Prod
        pool:
          name: server
        steps:
          - task: ServiceNow-DevOps-Server-Change-Acceleration@1
            inputs:
              connectedServiceName: 'devopstokyo139-Basic Project1-ServiceNow DevOps Service Connection'
              UpstreamJob: 'Job_Deploy'
              changeRequestDetails: |
                {
                  "setCloseCode": true,
                  "attributes": {
                    "requested_by": {
                        "name": "DevOps System"
                    },
                    "category": "DevOps",
                    "priority": "2",
                    "start_date": "2022-01-05 11:59:59",
                    "end_date": "2022-01-08 11:59:59",
                    "chg_model": {"name": "devops"},
                    "assignment_group": "a715cd759f2002002920bde8132e7018"
                    }
                }

          # - task: InvokeRESTAPI@1
          #   inputs:
          #     connectionType: 'connectedServiceName'
          #     serviceConnection: 'devopstokyo139-Basic Project1-Generic Connection'
          #     method: 'POST'
          #     body: |
          #       {
          #         "buildNumber":"$(build.buildId)",
          #         "isMultiBranch":"false",
          #         "branchName":"$(build.sourceBranchName)",
          #         "changeRequestDetails":{
          #           "setCloseCode": true,
          #           "attributes":{
          #             "chg_model": {"name": "DevOps"},
          #             "assignment_group":"a715cd759f2002002920bde8132e7018"
          #           }
          #         }
          #       }
          #     urlSuffix: 'api/sn_devops/v1/devops/orchestration/changeControl?toolId=a104cc8c47d93110bf04bf15126d4378&projectId=460440cc47d93110bf04bf15126d439b'
          #     waitForCompletion: 'true'

  
  # - stage: GETUPDATEchange
  #   dependsOn: Prod
  #   jobs:
  #     - job: Job_GETUPDATEchange
  #       steps:
  #         - task: Bash@3
  #           inputs:
  #             targetType: inline
  #             script: |
  #               # Write your commands here                  
  #               echo 'Hello world'
  #         - task: ServiceNow-DevOps-Agent-Get-Change@1
  #           inputs:
  #             connectedServiceName: 'devopsqerama92-Basic Project1-ServiceNow DevOps Service Connection'
  #             projectName: '$(system.teamProject)'
  #             pipelineName: '$(build.definitionName)'
  #             stageName: '$(System.StageName)'
  #             jobName: '$(System.JobDisplayName)'
  #             buildNumber: '$(build.buildId)'
  #             attemptNumber: '$(System.JobAttempt)'
  #             branchName: '$(Build.SourceBranchName)'
          
  #         - task: ServiceNow-DevOps-Agent-Update-Change@1
  #           inputs:
  #             connectedServiceName: 'devopsqerama92-Basic Project1-ServiceNow DevOps Service Connection'
  #             changeRequestNumber: 'CHG0030013'
  #             changeRequestDetails: |
  #               {
  #               "short_description": "Updating the short_description",
  #               "work_notes": "updated work notes",
  #               "description": "change description updating"
  #               }