name: CustomActionGetWorkflow
on: 
  workflow_dispatch:

jobs:
  changeApproval:
    name: ServiceNow DevOps Change Automation
    runs-on: ubuntu-latest
    steps:     
      - name: ServiceNow DevOps Change Automation
        uses: ServiceNow/servicenow-devops-change@main
        id: create
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow DevOps Change Automation'
          change-request: '{ "attributes": {"type": "normal", "template": "8935759bc36cf910f11d3641150131f8"}}'
          interval: '100'
          timeout: '3600'
